export const sessions = {
  'coming-home-to-yourself': {
    category: 'Self-Love',
    title: 'Coming Home to Yourself',
    intro: "For a long time, you've probably been the one everyone else comes home to. The one who remembers the school shoes, the meeting deadlines, the family events, the small emergencies. You've built a life around being needed — and there is real strength in that.",
    body: "But somewhere in all that giving, a question got quietly buried: what about you?\n\nComing home to yourself doesn't mean abandoning the people who need you. It means remembering that you are also a person who needs things — rest, softness, time that belongs to no one but you.",
    tryToday: "Think about the last time you did something just because you wanted to — not because it served your job, your children, your partner, or your business. Not \"self-care\" as another task on the list. Something that was simply for you.\n\nIf you can't remember, that's not a failure. That's just information. It tells you exactly where to begin.",
    smallStep: "Choose one thing this week — 15 minutes, no more — that belongs only to you. Not multitasked. Not squeezed between tasks. Just yours.",
    closing: "You don't need permission to matter to yourself. You already do.",
    journalPrompt: "What would I do today if I truly believed I mattered as much as everyone I take care of?",
  },
  'you-are-not-behind': {
    category: 'Self-Love',
    title: 'You Are Not Behind',
    intro: "You look at other women — the ones who seem to have it figured out, the perfect timeline, the \"arrived\" life — and something in your chest tightens. I should be further along by now.",
    body: "But further along than what, exactly? Whose clock are you measuring yourself against?\n\nThere is no universal deadline for healing, for business success, for finding love, for becoming who you're meant to be. Comparison steals your ability to see your own progress clearly.",
    tryToday: "Write down three things that are true about your life now that weren't true a year ago. Not achievements you're \"supposed\" to have — real, honest shifts, however small.",
    smallStep: "The next time you catch yourself comparing your timeline to someone else's, gently interrupt the thought with: \"I am exactly where my story requires me to be.\"",
    closing: "",
    journalPrompt: "What would I stop rushing if I truly believed I wasn't behind?",
  },
  'filling-your-own-cup-first': {
    category: 'Self-Love',
    title: 'Filling Your Own Cup First',
    intro: "You've likely heard \"you can't pour from an empty cup\" a hundred times — and rolled your eyes at it just as often, because who has time to fill their own cup when everyone else's needs come first?",
    body: "But an empty woman isn't a more devoted mother, partner, or businesswoman. She's just an exhausted one, running on reserves that were never meant to be permanent.\n\nSelf-care isn't selfish. It's the maintenance that keeps you able to keep showing up.",
    tryToday: "Notice where you say \"I don't have time\" — and ask honestly whether that's true, or whether it's guilt disguised as busyness.",
    smallStep: "Pick one small, non-negotiable ritual this week that refills you — five quiet minutes with your coffee before anyone wakes, a walk with no phone, closing your bedroom door for ten minutes of silence.",
    closing: "",
    journalPrompt: "What does my body/mind need right now that I've been ignoring?",
  },
  'grieving-whats-gone': {
    category: 'Breakup Healing',
    title: "Grieving What's Gone",
    intro: "Somewhere along the way, you might have gotten the message that breakup grief should be quick — get over it, move on, stay busy. But grief doesn't work on a deadline, and pretending it does just buries it deeper.",
    body: "What you lost was real. The future you imagined, the routines, the person you were within that relationship — all of it deserves to be mourned, not rushed past.",
    tryToday: "Give yourself permission to feel whatever comes up today, without judging it as \"too much\" or \"taking too long.\"",
    smallStep: "Say out loud, even just to yourself: \"This hurts because it mattered. I'm allowed to grieve it.\"",
    closing: "",
    journalPrompt: "What am I actually mourning — the person, the future I imagined, or a version of myself I lost along the way?",
  },
  'releasing-the-story-you-told-yourself': {
    category: 'Breakup Healing',
    title: 'Releasing the Story You Told Yourself',
    intro: "After a breakup, the mind loves to build a courtroom — replaying every conversation, searching for the moment it went wrong, assigning blame (often to yourself). What did I do wrong? Was I not enough?",
    body: "But not every ending has a villain. Sometimes two people simply grew in different directions, or wanted different things, or weren't right for each other despite loving each other.",
    tryToday: "Notice the story you keep repeating to yourself about \"why it ended.\" Ask: is this the whole truth, or the version fear wrote?",
    smallStep: "Write the story down once, fully — then write a second version that removes blame entirely, just facts. Notice how much lighter the second version feels.",
    closing: "",
    journalPrompt: "What would I need to believe about this ending to finally set it down?",
  },
  'rebuilding-after-heartbreak': {
    category: 'Breakup Healing',
    title: 'Rebuilding After Heartbreak',
    intro: "At some point, grief starts to make room for rebuilding — not forgetting, just no longer being consumed. This is where you start reintroducing yourself to your own life.",
    body: "Rebuilding isn't about erasing what happened. It's about proving to yourself, gently, that you're still capable of joy, connection, and forward motion.",
    tryToday: "Do one thing today that has nothing to do with the relationship that ended — something entirely, unmistakably yours.",
    smallStep: "Reconnect with one part of your identity that got smaller during the relationship — a friendship, a hobby, a version of your style or your voice.",
    closing: "",
    journalPrompt: "Who was I before, and what parts of her am I ready to welcome back?",
  },
  'your-children-will-leave-your-partner-stays': {
    category: 'Relationship & Partner Focus',
    title: 'Your Children Will Leave — Your Partner Stays',
    intro: "It's easy, especially as a mother, to let your partner slide quietly to the bottom of the list — beneath work, beneath the children, beneath everything urgent. It doesn't feel like a choice; it just happens, day by day.",
    body: "But here's the truth worth sitting with: your children are being raised to leave. That's the whole point — you're preparing them for a life beyond your home. Your partner, if the relationship survives, is the one who stays in the house after they go.\n\nThis isn't about loving your children less. It's about not losing your marriage while you're busy building theirs.",
    tryToday: "Ask yourself honestly — when did you last give your partner the kind of undivided attention you give your children?",
    smallStep: "This week, protect one small window of time that belongs only to the two of you — no phones, no children's names in the conversation.",
    closing: "",
    journalPrompt: "If my children left home tomorrow, would I recognize the relationship I'd be left with?",
  },
  'rekindling-intimacy': {
    category: 'Relationship & Partner Focus',
    title: 'Rekindling Intimacy',
    intro: "Intimacy doesn't only fade because love disappears — often it fades because life gets loud, and closeness needs quiet to grow. Between work, business, children, and simply surviving the day, \"us\" can quietly become an afterthought.",
    body: "Rekindling doesn't require grand gestures. It usually starts small — presence, touch, laughter, being truly seen again.",
    tryToday: "Notice the last time you and your partner laughed together, just the two of you, about nothing important.",
    smallStep: "Initiate one small moment of physical or emotional closeness today — a real hug, a genuine compliment, ten minutes of eye contact and conversation with the phones away.",
    closing: "",
    journalPrompt: "What made me feel closest to my partner in the beginning — and what's one way I could bring a piece of that back this week?",
  },
  'speaking-your-needs-without-guilt': {
    category: 'Relationship & Partner Focus',
    title: 'Speaking Your Needs Without Guilt',
    intro: "Many women are taught, quietly and over years, that needing something from a partner is \"asking too much\" — so instead of speaking up, they suppress, over-give, and quietly resent.",
    body: "But a relationship can't meet needs it never hears. Speaking your needs isn't demanding or ungrateful — it's giving your partner the chance to actually show up for you.",
    tryToday: "Notice one need you've been silently swallowing — for help, for affection, for time, for appreciation.",
    smallStep: "Say it out loud to your partner this week, clearly and without over-explaining or apologizing for having it.",
    closing: "",
    journalPrompt: "What do I need that I've been afraid to ask for — and what am I afraid will happen if I do?",
  },
}
